easy_admin:
    entities:
        Post:
            class: App\AppBundle\Entity\Post
            list:
                fields:
                    - { property: 'name', type: 'string'}
                    - { property: 'imageName', type: 'image', base_path: 'uploads/images/posts' }
                    - { property: 'category', type: 'string' }
            form:
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'content', type: 'textarea' }
                    - { property: 'imageFile', type: 'file' }
                    - { property: 'category', type: 'entity', type_options: {
                            class: 'App\AppBundle\Entity\Category',
                            choice_label: 'name'
                        }
                      }
        Category:
            class: App\AppBundle\Entity\Category
            form:
                fields:
                    - 'name'
                    - 'description'
        Comments:
            class: App\AppBundle\Entity\Comment
            form:
                fields:
                    - author
                    - content
                    - objectId
                    - objectName
